In [1]:
import numpy as np


In [2]:
np.ones()

TypeError: ones() missing 1 required positional argument: 'shape'

In [3]:
np.ones([5])

array([1., 1., 1., 1., 1.])

In [4]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [6]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
np.arange(5,50,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [8]:
5/2

2.5

In [10]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])

In [11]:
arr1*arr1

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [12]:
arr1**

SyntaxError: invalid syntax (2077810591.py, line 1)

In [13]:
arr1**3

array([[  1,   8,  27,  64],
       [125, 216, 343, 512]], dtype=int32)

In [14]:
1/arr1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     ]])

In [15]:
arr1[:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
arr1[:,:2]

array([[1, 2],
       [5, 6]])

In [21]:
arr_2d=np.zeros((10,10))

In [22]:
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [27]:
arr_length=arr_2d.shape[1]

In [28]:
for i in range(arr_length):
    arr_2d[i]=i
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [29]:
arr_2d[[0,3,5]]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [30]:
arr_2d[[9,1,7,2,4]]

array([[9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [32]:
new_arr= np.arange(50).reshape((10,5))

In [33]:
new_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [34]:
new_arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [35]:
np.dot(new_arr, new_arr.T)

array([[   30,    80,   130,   180,   230,   280,   330,   380,   430,
          480],
       [   80,   255,   430,   605,   780,   955,  1130,  1305,  1480,
         1655],
       [  130,   430,   730,  1030,  1330,  1630,  1930,  2230,  2530,
         2830],
       [  180,   605,  1030,  1455,  1880,  2305,  2730,  3155,  3580,
         4005],
       [  230,   780,  1330,  1880,  2430,  2980,  3530,  4080,  4630,
         5180],
       [  280,   955,  1630,  2305,  2980,  3655,  4330,  5005,  5680,
         6355],
       [  330,  1130,  1930,  2730,  3530,  4330,  5130,  5930,  6730,
         7530],
       [  380,  1305,  2230,  3155,  4080,  5005,  5930,  6855,  7780,
         8705],
       [  430,  1480,  2530,  3580,  4630,  5680,  6730,  7780,  8830,
         9880],
       [  480,  1655,  2830,  4005,  5180,  6355,  7530,  8705,  9880,
        11055]])

In [36]:
A= np.random.randn(10)
A

array([ 0.83333784,  0.07253538,  0.24561876, -0.37318528, -0.98347584,
        0.00562784,  1.15904043, -0.74079532, -0.06614644,  1.15805762])

In [37]:
B= np.random.randn(10)
B

array([ 1.13641366, -1.07460855,  0.0672482 , -1.02144856, -0.41859424,
       -0.63772556, -0.02369127,  0.54616063,  0.0578655 , -0.70792801])

In [38]:
np.maximum(A,B)

array([ 1.13641366,  0.07253538,  0.24561876, -0.37318528, -0.41859424,
        0.00562784,  1.15904043,  0.54616063,  0.0578655 ,  1.15805762])

In [39]:
np.minimum(A,B)

array([ 0.83333784, -1.07460855,  0.0672482 , -1.02144856, -0.98347584,
       -0.63772556, -0.02369127, -0.74079532, -0.06614644, -0.70792801])

In [40]:
np.amax(A)

1.1590404266963126

In [41]:
website='https://numpy.org/doc/stable/reference/generated/numpy.dot.html'
import webbrowser
webbrowser.open(website)

True

In [44]:
A_val= np.arange(1,5)
B_val= np.arange(100,500,100)
condition = np.array([True, True, False, False])
result = [(A_val if cond else B_val) for A_val, B_val,cond in zip(A_val, B_val, condition) ]
result

[1, 2, 300, 400]

In [45]:
result2= np.where(condition, B_val, A_val)
result2

array([100, 200,   3,   4])

In [46]:
from random import randn


ImportError: cannot import name 'randn' from 'random' (C:\Users\penev\anaconda3\lib\random.py)

In [47]:
from numpy.random import randn


In [48]:
arr3= randn(5,5)
arr3

array([[-0.55995741,  0.75507963, -2.36262759,  0.45908251, -1.47249764],
       [ 1.99751851,  0.96917197, -0.59695816,  2.70435878, -1.65832847],
       [ 2.00477547, -0.0183258 , -0.65743455,  0.05837056, -0.40583331],
       [-0.34787311,  0.8641579 ,  0.77739739,  1.85563735, -1.39143477],
       [ 1.00784009,  0.89587249,  1.29205435,  0.7820547 , -1.07368568]])

In [50]:
np.where(arr3<0,0,arr3)

array([[0.        , 0.75507963, 0.        , 0.45908251, 0.        ],
       [1.99751851, 0.96917197, 0.        , 2.70435878, 0.        ],
       [2.00477547, 0.        , 0.        , 0.05837056, 0.        ],
       [0.        , 0.8641579 , 0.77739739, 1.85563735, 0.        ],
       [1.00784009, 0.89587249, 1.29205435, 0.7820547 , 0.        ]])

In [52]:
arr4= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr4.sum()

78

In [53]:
arr4.sum(1)

array([10, 26, 42])

In [54]:
arr4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
arr4.sum(0)

array([15, 18, 21, 24])

In [57]:
arr4.mean()

6.5

In [59]:
arr5= np.arange(1,5)
np.save('my_arr', arr5)
np.load('my_arr.npy')

array([1, 2, 3, 4])

In [62]:
arr6=np.arange(5,11)
np.savez('zipped_arr', x= arr5, y=arr6)
zipped=np.load('zipped_arr.npz')

In [63]:
zipped

In [64]:
zipped['x']

array([1, 2, 3, 4])

In [65]:
zipped['y']

array([ 5,  6,  7,  8,  9, 10])